-- phpMyAdmin SQL Dump
-- version 4.9.3
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:8889
-- Généré le :  mer. 12 août 2020 à 11:29
-- Version du serveur :  5.7.26
-- Version de PHP :  7.4.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Base de données :  `starsinfos`
--
CREATE DATABASE IF NOT EXISTS `starsinfos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `starsinfos`;

-- --------------------------------------------------------

--
-- Structure de la table `stars`
--

CREATE TABLE `stars` (
  `id` int(11) NOT NULL,
  `firstname` varchar(100) NOT NULL,
  `lastname` varchar(100) NOT NULL,
  `description` text NOT NULL,
  `photo` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `stars`
--

INSERT INTO `stars` (`id`, `firstname`, `lastname`, `description`, `photo`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'Mary', 'Elizabeth Winstead', 'Mary Elizabeth Winstead (born November 28, 1984) is an American actress and singer. Her first significant role came as Jessica Bennett on the NBC soap opera Passions (1999–2000) and she went on to appear in TV series such as Tru Calling (2004) and films including the superhero film Sky High (2005). She came to wider attention as a Scream Queen[1][2] for her roles in the horror series Wolf Lake (2001–2002), the giant monster film Monster Island (2004), the supernatural horror film Final Destination 3 (2006), the slasher film Black Christmas (2006) and the exploitation horror film Death Proof (2007).\r\n\r\nFurther success came with her roles as John McClane\'s daughter Lucy Gennero-McClane in Live Free or Die Hard (2007) and Ramona Flowers in Scott Pilgrim vs. the World (2010). Her critically acclaimed-performance as an alcoholic struggling with sobriety in the Sundance drama Smashed (2012) was followed by a series of roles in other well-received independent films, including The Beauty Inside (2012), The Spectacular Now (2013), Faults (2014), Alex of Venice (2014) and Swiss Army Man (2016). Winstead continued her Scream Queen roles in the body horror film The Thing (2011), as Mary Todd Lincoln in the fantasy horror film Abraham Lincoln: Vampire Hunter (2012) and in the psychological horror thriller film 10 Cloverfield Lane (2016).\r\n\r\nShe reprised her role as Lucy Gennero-McClane in A Good Day to Die Hard (2013) and returned to television with roles in the supernatural drama series The Returned (2015), the political satire/science fiction comedy series BrainDead (2016), the period medical drama series Mercy Street (2016–17) and the black comedy/crime drama anthology series Fargo (2017). Her recent roles include the comedy drama All About Nina (2018), the action thriller Gemini Man (2019) and as the Huntress in Birds of Prey (2020).\r\n\r\nSince 2013, Winstead has performed as half of the music duo Got a Girl, with Dan the Automator.', 'rcME8oUFIcpo3aeWzDhiVOxpTLgEgPKhGZjaLaDw.jpeg', '2020-08-12 10:34:41', '2020-08-12 10:34:41', NULL),
(2, 'Idris', 'Elba', 'Idrissa Akuna Elba OBE (born 6 September 1972) is an English actor, writer, producer, rapper, singer, songwriter and DJ.[3] He is known for roles including Stringer Bell in the HBO series The Wire,[4] DCI John Luther in the BBC One series Luther, and Nelson Mandela in the biographical film Mandela: Long Walk to Freedom (2013). He has been nominated four times for a Golden Globe Award for Best Actor – Miniseries or Television Film, winning one, and was nominated five times for a Primetime Emmy Award.[5][6]\r\n\r\nElba appeared in Ridley Scott\'s American Gangster (2007) and Prometheus (2012). Elba portrayed Heimdall in Thor (2011) and its sequels Thor: The Dark World (2013) and Thor: Ragnarok (2017), as well as Avengers: Age of Ultron (2015) and Avengers: Infinity War (2018). He also starred in Pacific Rim (2013), Beasts of No Nation (2015), for which he received BAFTA and Golden Globe nominations for Best Supporting Actor, and Molly\'s Game (2017). In 2016, he voiced Chief Bogo in Zootopia, Shere Khan in the live action/CGI adaptation of The Jungle Book, Fluke in Finding Dory, and played the role of Krall in Star Trek Beyond. He made his directorial debut in 2018 with an adaptation of the 1992 novel Yardie by Victor Headley.[7]\r\n\r\nIn addition to his acting work, Elba performs as a DJ under the moniker DJ Big Driis (or Big Driis the Londoner) and as an R&B musician.[8] In 2016, he was named in the Time 100 list of the Most Influential People in the World.[9] As of May 2019, his films have grossed over $9.8 billion at the global box office, including over $3.6 billion in North America,[10] where he is one of the top 20 highest-grossing actors.', 'KeL3k2q2dMuLwseNaLOWe9KfGA1P4IQoaXa6wl8b.jpeg', '2020-08-12 10:40:00', '2020-08-12 10:43:05', NULL),
(3, 'Leonardo', 'DiCaprio', 'Leonardo Wilhelm DiCaprio (born November 11, 1974) is an American actor, producer, philanthropist, and environmentalist. He has often played unconventional parts, particularly in biopics, drama, crime, romance, and period films. As of 2019, his films have grossed US$7.2 billion worldwide, and he has placed eight times in annual rankings of the highest-paid actors in the world.\r\n\r\nBorn in Los Angeles, DiCaprio began his career by appearing in television commercials in the late 1980s. In the early 1990s, he played recurring roles in various television series, such as the sitcom Parenthood. He had his first major film role in This Boy\'s Life (1993), and received acclaim for his supporting role as a developmentally disabled boy in What\'s Eating Gilbert Grape (1993). He achieved international stardom in the epic romance Titanic (1997), which became the highest-grossing film to that point. After a few commercially unsuccessful films, DiCaprio starred in two successful features in 2002: the biographical crime drama Catch Me If You Can and the historical drama Gangs of New York, which marked his first of many collaborations with director Martin Scorsese.\r\n\r\nDiCaprio later portrayed Howard Hughes in The Aviator (2004) and a mercenary in the political thriller Blood Diamond (2006), and he also received acclaim for his performances in the crime drama The Departed (2006) and the romantic drama Revolutionary Road (2008). In the 2010s, he starred in the science fiction thriller Inception (2010), the western Django Unchained (2012), the biopic The Wolf of Wall Street (2013), the survival drama The Revenant (2015), and the comedy-drama Once Upon a Time in Hollywood (2019), all of which were critical and commercial successes. His accolades include an Academy Award, a BAFTA, and a Golden Globe Award for The Revenant as well as two other Golden Globes for The Aviator and The Wolf of Wall Street.\r\n\r\nDiCaprio is the founder of Appian Way Productions—a production company that has produced some of his films and the documentary series Greensburg (2008–2010)—and the Leonardo DiCaprio Foundation, a non-profit organization devoted to promoting environmental awareness. He regularly supports charitable causes, and has produced several documentaries on the environment. In 2005, he was named the commander of the Ordre des Arts et des Lettres for his contributions to the arts, and in 2016, he was listed as one of the 100 most influential people in the world by Time magazine.', '5W9n0Awk1THG1Gn37xDEEmZJCyoJeI5AkRrkfAU2.jpeg', '2020-08-12 10:42:23', '2020-08-12 10:48:03', NULL),
(4, 'Brie', 'Larson', 'Brianne Sidonie Desaulniers (born October 1, 1989), known professionally as Brie Larson, is an American actress and filmmaker. Noted for her supporting work in comedies when a teenager, she has since expanded to leading roles in independent dramas and film franchises, receiving such accolades as an Academy Award and a Golden Globe. Time magazine named her one of the 100 most influential people in the world in 2019.\r\n\r\nBorn in Sacramento, California, Larson was homeschooled. At age six, she became the youngest student admitted to a training program at the American Conservatory Theater. She soon relocated to Los Angeles and began her acting career in 1998 with a comedy sketch in The Tonight Show with Jay Leno. She appeared as a regular in the 2001 sitcom Raising Dad and briefly dabbled with a music career, releasing the album Finally Out of P.E. in 2005. Larson subsequently played supporting roles in the comedy films Hoot (2006), Scott Pilgrim vs. the World (2010), and 21 Jump Street (2012), and appeared as a sardonic teenager in the television series United States of Tara (2009–2011).\r\n\r\nLarson\'s breakthrough came with a leading role in the acclaimed independent drama Short Term 12 (2013), and she continued to take on supporting parts in the romance The Spectacular Now (2013) and the comedy Trainwreck (2015). For playing a kidnapping victim in the drama Room (2015), Larson won the Academy Award for Best Actress. The 2017 adventure film Kong: Skull Island marked her first big-budget release, after which she starred as Carol Danvers in the 2019 Marvel Cinematic Universe superhero films Captain Marvel and Avengers: Endgame.\r\n\r\nLarson has also co-written and co-directed two short films, including The Arm (2012), which received a special jury prize at the Sundance Film Festival. She made her feature film directorial debut in 2017 with the independent comedy-drama Unicorn Store. A gender equality activist and an advocate for sexual assault survivors, Larson is vocal about social and political issues.', 'Wv1t8Jzfizwxgw6Fq6cQScEvD2BnF6xV1Pbq3xp1.jpeg', '2020-08-12 10:44:06', '2020-08-12 10:44:17', NULL),
(5, 'Natalie', 'Portman', 'Natalie Portman (born June 9, 1981) is an actress and filmmaker with dual Israeli and American citizenship. Prolific in film since a teenager, she has starred in blockbusters and also played psychologically troubled women in independent films, for which she has received various accolades, including an Academy Award and two Golden Globe Awards.\r\n\r\nPortman began her acting career at age 12 by starring as the young protégée of a hitman in the action drama film Léon: The Professional (1994). While in high school, she made her Broadway theatre debut in a 1998 production of The Diary of a Young Girl and gained international recognition for starring as Padmé Amidala in Star Wars: Episode I – The Phantom Menace (1999). From 1999 to 2003, Portman attended Harvard University for a bachelor\'s degree in psychology, while continuing to act in the Star Wars prequel trilogy (2002, 2005) and in The Public Theater\'s 2001 revival of Anton Chekhov\'s play The Seagull. In 2004, Portman was nominated for an Academy Award for Best Supporting Actress and won a Golden Globe Award for playing a mysterious stripper in the romantic drama Closer.\r\n\r\nPortman\'s career progressed with her starring roles as Evey Hammond in V for Vendetta (2006), Anne Boleyn in The Other Boleyn Girl (2008), and a troubled ballerina in the psychological horror film Black Swan (2010), for which she won the Academy Award for Best Actress. She went on to star in the romantic comedy No Strings Attached (2011) and featured as Jane Foster in the Marvel Cinematic Universe superhero films Thor (2011), and Thor: The Dark World (2013), which established her among the best-paid actresses in the world. She has since portrayed Jacqueline Kennedy in the biopic Jackie (2016), gaining her third Academy Award nomination, and a biologist in the science fiction film Annihilation (2018).\r\n\r\nPortman\'s directorial ventures include the short film Eve (2008) and the biographical drama A Tale of Love and Darkness (2015). She is vocal about the politics of America and Israel, and is an advocate for animal rights and environmental causes. She is married to dancer and choreographer Benjamin Millepied, with whom she has two children.', 'CuRAHU5RI2Hb4rU8RMNj3OIhhe2Yyr0MWHAWkcCd.jpeg', '2020-08-12 10:57:46', '2020-08-12 10:57:46', NULL),
(6, 'Ewan', 'McGregor', 'Ewan Gordon McGregor OBE (/ˈjuːən/ YOO-ən;[1] born 31 March 1971[2]) is a Scottish actor known internationally for his various film roles, including independent dramas, science-fiction epics, and musicals.\r\n\r\nMcGregor\'s first professional role was in 1993, when he won a leading role in the British Channel 4 series Lipstick on Your Collar.[3] Some of his best known roles include heroin addict Mark Renton in the drama films Trainspotting (1996) and T2 Trainspotting (2017), Obi-Wan Kenobi in the Star Wars prequel trilogy (1999–2005), poet Christian in the musical film Moulin Rouge! (2001), young Edward Bloom in Big Fish (2003), Rodney Copperbottom in Robots (2005), Camerlengo Father Patrick McKenna in Angels and Demons (2009), \"the ghost\" in Roman Polanski\'s political thriller The Ghost Writer (2010), Dr. Alfred Jones in the romantic comedy-drama Salmon Fishing in the Yemen (2011), Lumière in the live-action adaptation of the musical romantic fantasy Beauty and the Beast (2017), the adult version of the titular character in the fantasy comedy-drama Christopher Robin (2018) and the adult version of Dan Torrance in the horror film Doctor Sleep (2019). He also appeared as Black Mask in DC Extended Universe superhero film Birds of Prey (2020).\r\n\r\nIn 2018, McGregor won a Golden Globe Award for Best Actor – Miniseries or Television Film for his performance as brothers in the third season of FX anthology series Fargo, and received Golden Globe nominations for Best Actor – Musical or Comedy for both Moulin Rouge! and Salmon Fishing in the Yemen. McGregor has also starred in theatre productions of Guys and Dolls (2005–07) and Othello (2007–08). He was ranked number 36 on Empire magazine\'s \"The Top 100 Movie Stars of All Time\" list in 1997.[4] In a 2004 poll for the BBC, McGregor was named the fourth most influential person in British culture.[5][6]\r\n\r\nMcGregor has been involved in charity work and has served as an ambassador for UNICEF UK since 2004. In 2013, he was appointed an Officer of the Order of the British Empire (OBE) for services to drama and charity. In 2016, he received the BAFTA Britannia Humanitarian Award.', 'xraTrmSQxck74j9QLYkyXZfjys55boCorxb4X7rf.jpeg', '2020-08-12 10:58:41', '2020-08-12 10:58:41', NULL),
(7, 'Helena', 'Bonham Carter', 'Helena Bonham Carter (born 26 May 1966) is an English actress. She is known for her roles in independent films and large-scale blockbusters. She was nominated for the Academy Award for Best Actress for her role as Kate Croy in The Wings of the Dove (1997) and for the Academy Award for Best Supporting Actress and won the BAFTA Award for Best Actress in a Supporting Role for her role as Queen Elizabeth in The King\'s Speech (2010). She also won the 2010 International Emmy Award for Best Actress and was nominated for the British Academy Television Award for Best Actress for her role as author Enid Blyton in the BBC Four television film Enid (2009).\r\n\r\nBonham Carter began her film career playing Lucy Honeychurch in A Room with a View (1985) and the title character in Lady Jane (1986). Her other films include Hamlet (1990), Howards End (1992), Mary Shelley\'s Frankenstein (1994), Woody Allen\'s Mighty Aphrodite (1995), The Wings of the Dove (1997), Fight Club (1999), Bellatrix Lestrange in the Harry Potter series (2007–11), Miss Havisham in Great Expectations (2012), Madame Thénardier in Les Misérables (2012), the Fairy Godmother in Cinderella (2015), and Rose Weil in Ocean\'s 8 (2018). Her frequent collaborations with director Tim Burton include Big Fish (2003), Corpse Bride (2005), Charlie and the Chocolate Factory (2005), Sweeney Todd: The Demon Barber of Fleet Street (2007), Alice in Wonderland (2010) and Dark Shadows (2012). Her television films include Fatal Deception: Mrs. Lee Harvey Oswald (1993), Live from Baghdad (2002), Toast (2010), and Burton & Taylor (2013). In 2018, she was confirmed to play Princess Margaret on seasons three and four of The Crown.\r\n\r\nBonham Carter was made a Commander of the Order of the British Empire (CBE) in the 2012 New Year Honours list for services to drama,[1] and Prime Minister David Cameron announced that she had been appointed to Britain\'s new national Holocaust Commission in January 2014.', 'IlGRDxUKTtzJ94OZ7H7HaumUPDuj70RoegWLaB7s.jpeg', '2020-08-12 11:02:07', '2020-08-12 11:02:42', NULL),
(8, 'Robert', 'Downey Jr.', 'Robert John Downey Jr. (born April 4, 1965)[1] is an American actor, producer, and singer. His career has been characterized by critical and popular success in his youth, followed by a period of substance abuse and legal troubles, before a resurgence of commercial success in middle age. In 2008, Downey was named by Time magazine among the 100 most influential people in the world,[2][3] and from 2013 to 2015, he was listed by Forbes as Hollywood\'s highest-paid actor.[2][4] His films have grossed over $14.4 billion worldwide,[5] making him the second highest-grossing box-office star of all time.[6]\r\n\r\nAt the age of five, he made his acting debut in Robert Downey Sr.\'s film Pound in 1970. He subsequently worked with the Brat Pack in the teen films Weird Science (1985) and Less Than Zero (1987). In 1992, Downey portrayed the title character in the biopic Chaplin, for which he was nominated for the Academy Award for Best Actor and won a BAFTA Award. Following a stint at the Corcoran Substance Abuse Treatment Facility on drug charges, he joined the TV series Ally McBeal, for which he won a Golden Globe Award; however in the wake of two drug charges, one in late 2000 and one in early 2001, he was fired and his character terminated. He stayed in a court-ordered drug treatment program shortly after and has maintained his sobriety since 2003.\r\n\r\nInitially, bond completion companies would not insure Downey, until Mel Gibson paid the insurance bond for the 2003 film The Singing Detective.[7] He subsequently went on to star in the black comedy Kiss Kiss Bang Bang (2005), the thriller Zodiac (2007), and the action comedy Tropic Thunder (2008); for the latter he was nominated for an Academy Award for Best Supporting Actor. Downey gained global recognition for starring as Tony Stark / Iron Man in ten films within the Marvel Cinematic Universe, beginning with Iron Man (2008). He has also played the title character in Guy Ritchie\'s Sherlock Holmes (2009), which earned him his second Golden Globe, and its sequel (2011).', 'DaZsuhLqYUQNdHY5bx9IvOM33cJWQRUlBFsFS0G5.jpeg', '2020-08-12 11:05:12', '2020-08-12 11:05:12', NULL),
(9, 'Bryan', 'Cranston', 'Bryan Lee Cranston (born March 7, 1956) is an American actor, director, producer, and screenwriter. He is best known for his roles as Tim Whatley in the NBC sitcom Seinfeld (1994–1997), Hal in the Fox sitcom Malcolm in the Middle (2000–2006), Walter White in the AMC crime drama series Breaking Bad (2008–2013), and Vince Lonigan in the Prime Video crime drama series Sneaky Pete (2015–2019).\r\n\r\nCranston\'s performance on Breaking Bad is widely regarded as one of the best in television history, earning him the Primetime Emmy Award for Outstanding Lead Actor in a Drama Series four times (2008, 2009, 2010, and 2014).[1] After becoming a producer of the show in 2011, he also won the award for Outstanding Drama Series twice.[2] Breaking Bad also earned Cranston five Golden Globe nominations (with one win), nine Screen Actors Guild Award nominations (with four wins), and six Satellite Award nominations (with four wins). He was previously nominated three times for the Outstanding Supporting Actor in a Comedy Series for his role in Malcolm in the Middle. Cranston co-created, executive produced, and wrote the story for the crime drama series Sneaky Pete (with David Shore) and the comedy drama series The Dangerous Book for Boys (with Greg Mottola).[3]\r\n\r\nIn 2014, Cranston earned a Tony Award for Best Actor in a Play for his portrayal of president Lyndon B. Johnson in the Broadway play All the Way, a role he reprised in HBO\'s 2016 television film of the same name. In 2018, he received the Laurence Olivier Award for Best Actor for his portrayal of Howard Beale in the play Network at London\'s National Theatre, later winning his second Tony Award for playing the same role on Broadway. For portraying Dalton Trumbo in the film Trumbo (2015), he garnered acclaim and a nomination for the Academy Award for Best Actor.\r\n\r\nCranston has directed episodes of Malcolm in the Middle, Breaking Bad, Modern Family, and The Office. He has also appeared in several acclaimed films, such as Saving Private Ryan (1998), Little Miss Sunshine (2006), Drive (2011), Argo (2012), Godzilla (2014), and The Upside (2017). He also provided voice acting in the films Madagascar 3: Europe\'s Most Wanted (2012), Kung Fu Panda 3 (2016), and Isle of Dogs (2018).', 'Mz85gUk2MTzahAaiMHsD1uIHXzsNPOb7SaaUddLo.jpeg', '2020-08-12 11:06:11', '2020-08-12 11:06:11', NULL),
(10, 'Keira', 'Knightley', 'Keira Christina Knightley (born 26 March 1985) is a British actress. Her starring roles in independent films, and period dramas as well as big-budget blockbuster productions have earned her nominations for two British Academy Film Awards, three Golden Globe Awards, three British Independent Film Awards and two Academy Awards.\r\n\r\nKnightley began acting as a child on television and made her feature film debut in 1995, before making her breakthrough with the 2002 sports film Bend It Like Beckham, for which she won the London Film Critics\' Circle Award for Best Newcomer. She gained wider recognition for playing Elizabeth Swann in the 2003 fantasy swashbuckler film Pirates of the Caribbean. Knightley reprised the role in the subsequent films of the franchise.\r\n\r\nKnightley received a nomination for the Academy Award for Best Actress for starring as Elizabeth Bennet in Pride & Prejudice (2005) and later became known for starring in several other period dramas, earning praise for her roles as Cecilia Tallis in Atonement (2007), Georgiana Cavendish in The Duchess (2008) and the titular characters in Anna Karenina (2012) and Colette (2018). Knightley received her second Academy Award nomination for portraying Joan Clarke in the historical film The Imitation Game (2014), as she continued to experiment with comedic and dramatic roles in the musical film Begin Again (2013), the adventure thriller Everest (2015), and the docudrama Official Secrets (2019).\r\n\r\nOn stage, Knightley appeared in Martin Crimp\'s 2009 West End production of The Misanthrope, which earned her a nomination for a Laurence Olivier Award. She also starred as the eponymous heroine in the 2015 Broadway production of Thérèse Raquin. Knightley is known for her outspoken stance on social issues, and has worked extensively with Amnesty International, Oxfam, and Comic Relief. She was appointed an OBE in the 2018 Birthday Honours for services to drama and charity.', 'jvuAGgBDKy0HAKIHoYtnBAq9bdNqrrSR2IrYBZBx.jpeg', '2020-08-12 11:06:59', '2020-08-12 11:09:54', NULL);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `stars`
--
ALTER TABLE `stars`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `stars`
--
ALTER TABLE `stars`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;
